# config/packages/doctrine.yaml

# doctrine:
#     dbal:
#         # Configure your db driver and connection here if using a database
#         # url: '%env(resolve:DATABASE_URL)%'
#         # driver: 'pdo_mysql'
#         # server_version: '8.0'
#         # charset: utf8mb4
#
#         # idle_connection_ttl: 600
#         # default_table_options:
#         #     charset: utf8mb4
#         #     collate: utf8mb4_unicode_ci
#         # profiling_collect_backtrace: '%kernel.debug%'
#         # use_savepoints: true
#
#     orm:
#         # auto_generate_proxy_classes: true
#         # enable_lazy_ghost_objects: true
#         # naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#         # auto_mapping: true
#         # mappings:
#         #     App:
#         #         type: attribute
#         #         dir: '%kernel.project_dir%/src/Entity'
#         #         prefix: 'App\Entity'
#         #         alias: App
#
#         # validate_xml_mapping: true
#         # identity_generation_preferences:
#         #     Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
#
#     # Optional: disable second-level cache if configured
#     # orm_second_level_cache:
#     #     enabled: false
#
# when@test:
#     doctrine:
#         dbal:
#             # test database suffix if using tests with database
#             # dbname_suffix: '_test%env(default::TEST_TOKEN)%'
#
# when@prod:
#     doctrine:
#         orm:
#             # Disable proxy class auto generation in production
#             auto_generate_proxy_classes: false
#             proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
#             query_cache_driver:
#                 type: pool
#                 pool: doctrine.system_cache_pool
#             result_cache_driver:
#                 type: pool
#                 pool: doctrine.result_cache_pool
#
#     framework:
#         cache:
#             pools:
#                 doctrine.result_cache_pool:
#                     adapter: cache.app
#                 doctrine.system_cache_pool:
#                     adapter: cache.system_cache_pool





