security:
  password_hashers:
    # Updated to your user class in Auth module namespace
    App\Auth\Security\JsonUser:
      algorithm: auto

  providers:
    intrusec_user_provider:
      id: App\Auth\Security\JsonUserProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: intrusec_user_provider

      custom_authenticators:
        - App\Auth\Security\IntrucustomAuthenticator

      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true
        csrf_token_id: authenticate

      entry_point: App\Auth\Security\IntrucustomAuthenticator

      logout:
        path: app_logout
        target: app_login

      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800   # 1 week
        path: /
        always_remember_me: false

  access_control:
    - { path: ^/login$, roles: PUBLIC_ACCESS }
    - { path: ^/register$, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: ROLE_USER }

