security:
  

  password_hashers:
    App\Entity\Intrusec:
      algorithm: auto

  providers:
    intrusec_user_provider:
            id: App\Security\JsonUserProvider
    #intrusec_user_provider:
     # entity:
      #  class: App\Entity\Intrusec
       # property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
      
    main:
      lazy: true
      provider: intrusec_user_provider
      
      custom_authenticators:
        - App\Security\IntrucustomAuthenticator

      logout:
        path: app_logout
        target: app_login

      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800     # 1 week in seconds
        path: /
        always_remember_me: false

  access_control:
    - { path: ^/login$, roles: PUBLIC_ACCESS }
    - { path: ^/register$, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: ROLE_USER }







