# config/services.yaml
parameters:
    # default parameters can be here

services:
    _defaults:
        autowire: true      # Automatically inject dependencies in your services
        autoconfigure: true # Automatically register your services as commands, event subscribers, etc.
        public: false       # Services should be private by default

    # Your user storage service with project directory parameter
    #App\Service\UserStorageService: 
    App\Service\UserStorageService:
         autowire: true
         autoconfigure: true

        #arguments:
         #   $projectDir: '%kernel.project_dir%'
          #  $userStorage: '@App\Service\UserStorageService'
             
    # Your custom authenticator with automatic wiring of UrlGeneratorInterface
    App\Security\IntrucustomAuthenticator: ~

    # Controllers are usually public
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        public: true

            
