# config/services.yaml

parameters:
    # You can add custom parameters here if needed

services:
    _defaults:
        autowire: true        # Automatically inject dependencies
        autoconfigure: true   # Automatically configure for Symfony features
        public: false         # Services are private by default

    # UserStorageService explicitly receives the project directory path
    App\Service\UserStorageService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    # Custom user provider with injected UserStorageService
    App\Security\JsonUserProvider:
        arguments:
            $userStorage: '@App\Service\UserStorageService'

    # Custom authenticator with autowired dependencies
    App\Security\IntrucustomAuthenticator: ~

    # Auto-register controllers, make them public
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        public: true





